### ISSUE TITLE
vscode is crippled

### ISSUE THREAD

**Issue by bkeys** [fusion809/vscode-installer#1]
Hello, would you mind incorporating my product.json file which decripples vscode? It gives easy access to the market place back. You can look at my vscode-decrippled here
https://notabug.org/bkeys/vscode-decrippled

**Comment by fusion809** [comment]
We used to but that makes the resulting VSCode proprietary and not open-source. So I decided to remove the patch that 'fixed' this issue.

**Comment by bkeys** [comment]
But if you add only the section that mentions the marketplace it should not pass the threshold of originality, and as such is not an object of copyright.
